CREATE TABLE clinical_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    patient_id VARCHAR(30),
    diagnosis_age FLOAT NULL,
    sex VARCHAR(20),
    race_category VARCHAR(100),
    ethnicity_category VARCHAR(100),
    years_smoked FLOAT NULL,
    pack_years FLOAT NULL,
    ajcc_stage VARCHAR(30),
    t_stage VARCHAR(20),
    n_stage VARCHAR(20),
    m_stage VARCHAR(20),
    primary_diagnosis TEXT,
    overall_survival_months DOUBLE NULL,
    overall_survival_status VARCHAR(50),
    disease_free_months DOUBLE NULL,
    disease_free_status VARCHAR(100),
    mutation_count FLOAT NULL,
    fraction_genome_altered DOUBLE NULL,
    vital_status VARCHAR(20),
    year_of_diagnosis INT NULL,
    age_group VARCHAR(20)
);